
onnx_path: "accad_female_b1_30000.onnx"
# onnx_path: "kungfu_5000.onnx"
# onnx_path: "model_65000.onnx"

# motion_length: 35.3 #lanfan 1000
motion_length: 7.23 #female b1
kps: [100, 100, 100, 150, 40, 40,
            100, 100, 100, 150, 40, 40,
            400, 400, 400,
            100,   100,  50, 50, 20, 20, 20,
            100,   100,  50, 50, 20, 20, 20
            ]

kds: [2.0, 2.0, 2.0, 4.0, 2.0, 2.0,
            2.0, 2.0, 2.0, 4.0, 2.0, 2.0,
            5.0, 5.0, 5.0,
            2.0, 2.0, 2.0, 2.0, 0.4, 0.4, 0.4,
            2.0, 2.0, 2.0, 2.0, 0.4, 0.4, 0.4
            ]

tau_limit: [88, 88, 88, 139, 50, 50,
            88, 88, 88, 139, 50, 50,
            88, 50, 50,
            25, 25, 25, 25, 5, 5, 5,
            25, 25, 25, 25, 5, 5, 5
           ]

default_angles: [-0.1,  0.0,  0.0,  0.3, -0.2, 0.0, 
                 -0.1,  0.0,  0.0,  0.3, -0.2, 0.0,
                  0.0, 0.0, 0.0, 
                  # 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
                  # 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
                  0.2, 0.2, 0.0, 0.9, 0.0, 0.0, 0.0,
                  0.2, -0.2, 0.0, 0.9, 0.0, 0.0, 0.0,
                  # 0.35, 0.18, 0.0, 0.87, 0.0, 0.0, 0.0
                  ]

dof23_index: [ 0, 1, 2, 3, 4, 5,
               6, 7, 8 ,9 ,10, 11,
               12, 13, 14,
               15, 16, 17, 18,
               22, 23, 24, 25
             ]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
history_length: 4
num_actions: 23
num_obs: 380